version: "3"

services:
  myapp:
    build: ./ 
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      back-end:
        aliases:
          - myapp
    environment:
      - PORT=3000
  front:
    build: ./front
    ports:
      - 4000:3000
    depends_on:
      - myapp
    networks:
      back-end:
        aliases:
          - front
    environment:
      - REACT_APP_BACKEND=localhost:3000
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345678"
    networks:
      back-end:
        aliases:
          - db
networks:
  back-end: